services:
  backend:
    build:
      context: .
      dockerfile: ./grading-admin-service/Dockerfile
    env_file:
      - .env
    environment:
      S3_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./certificates/certs/localhost-root/localhost-root.CA.pem:/certificates/localhost-root.CA.crt
    depends_on:
      authentik-sidecar:
        condition: service_completed_successfully
      grading-admin-postgres:
        condition: service_healthy
      certificates:
        condition: service_completed_successfully
      localhost.dev-int:
        condition: service_started

  frontend:
    build: ./grading-admin-web
    restart: unless-stopped
    env_file:
      - .env

  authentik:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.12.1}
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgres
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    volumes:
      - ./authentik/media:/media
      - ./authentik/custom-templates:/templates
      - ./authentik/healthcheck.sh:/opt/usr/healthcheck.sh
    env_file:
      - .env
    depends_on:
      authentik-postgres:
        condition: service_healthy
      authentik-redis:
        condition: service_healthy
      authentik-worker:
        condition: service_started

  authentik-worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.12.1}
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgres
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    volumes:
      - ./authentik/media:/media
      - ./authentik/certs:/certs
      - ./authentik/custom-templates:/templates
    env_file:
      - .env
    depends_on:
      authentik-postgres:
        condition: service_healthy
      authentik-redis:
        condition: service_healthy
  grading-admin-postgres:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - grading-admin-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-gradingadmin}
      POSTGRES_DB: ${PG_DB:-gradingadmindb}
    env_file:
      - .env
  authentik-postgres:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - authentik-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-gradingadmindb}
    env_file:
      - .env
  authentik-redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - authentik-redis-store:/data
  grading-policy-service:
    build: ./grading-policy-service
    command:
      - /opt/config.yaml
    volumes:
      - "./grading-policy-service/config.yaml:/opt/config.yaml"
  minio:
    image: minio/minio:latest
    command: server /data
    healthcheck:
      test: mc ready local
    env_file:
      - .env
    volumes:
      - minio-store:/data

  rabbitmq:
    image: rabbitmq:4-alpine
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - "./rabbitmq/rabbitmq.conf:/etc/rabbitmq/conf.d/100-conf.conf"

# UTILS
  certificates:
    build:
      context: certificates/
      dockerfile: Dockerfile
    environment:
      DOMAIN: ${DOMAIN:-localhost.dev}
      EMAIL: ${EMAIL:-gradingadmin@localhost}
      ENVIRONMENT: ${ENVIRONMENT:-development}
    volumes:
      - ./certificates/certs:/opt/certs:rw
  authentik-sidecar:
    build:
      context: authentik-sidecar
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - "./authentik-sidecar/users:/app/users"
    depends_on:
      authentik:
          condition: service_healthy

  openapi-docs:
    build:
      context: openapi
      dockerfile: Dockerfile

# PROXY
  localhost.dev-int:
    hostname: localhost.dev
    image: 'nginx:alpine'
    volumes:
      - "./nginx/services/backend-integration.nginx.conf:/etc/nginx/services/backend.nginx.conf"
      - "./nginx/services/frontend-integration.nginx.conf:/etc/nginx/services/frontend.nginx.conf"
      - "./nginx/services/database-integration.nginx.conf:/etc/nginx/services/database.nginx.conf"
      - "./nginx/services/minio-integration.nginx.conf:/etc/nginx/services/minio.nginx.conf"
      - "./nginx/services/rabbitmq-integration.nginx.conf:/etc/nginx/services/rabbitmq.nginx.conf"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./certificates/certs/localhost.dev/out:/etc/ssl/localhost.dev:ro"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      authentik:
        condition: service_healthy
      certificates:
        condition: service_completed_successfully
      openapi-docs:
        condition: service_started
      grading-policy-service:
        condition: service_healthy

  localhost.dev-local:
    hostname: localhost.dev
    image: 'nginx:alpine'
    profiles:
      - local
    ports:
      - "80:80"
      - "443:443"
      - "5432:5432"
      - "9000:9000"
      - "5672:5672"
    volumes:
      - "./nginx/services/backend-local.nginx.conf:/etc/nginx/services/backend.nginx.conf"
      - "./nginx/services/frontend-local.nginx.conf:/etc/nginx/services/frontend.nginx.conf"
      - "./nginx/services/database-local.nginx.conf:/etc/nginx/services/database.nginx.conf"
      - "./nginx/services/minio-local.nginx.conf:/etc/nginx/services/minio.nginx.conf"
      - "./nginx/services/rabbitmq-local.nginx.conf:/etc/nginx/services/rabbitmq.nginx.conf"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./certificates/certs/localhost.dev/out:/etc/ssl/localhost.dev:ro"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      authentik:
        condition: service_healthy
      grading-admin-postgres:
        condition: service_healthy
      authentik-sidecar:
        condition: service_completed_successfully
      certificates:
        condition: service_completed_successfully
      openapi-docs:
        condition: service_started
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      grading-policy-service:
        condition: service_started

volumes:
  grading-admin-db:
    driver: local
  authentik-db:
    driver: local
  authentik-redis-store:
    driver: local
  minio-store:
    driver: local
