openapi: 3.0.0
info:
  title: Grading Admin
  description: |
    This API defines the operations required manage grades for classes
    that utilize multiple platforms while respecting custom late policies
  version: 0.0.1
  license:
    name: MIT
servers:
  - url: https://localhost.dev/api
    description: Local Development
security:
  - openIDC:
      - user:read
tags:
  - name: health
    description: Health checks for grading server
  - name: admin
    description: Administration functions for the grading server
  - name: user
    description: User management functions for the grading server
  - name: tasks
    description: Async task service for the grading server
paths:
  /-/health:
    $ref: paths/-_health.yml
  /admin/courses:
    $ref: paths/admin_courses.yml
  /admin/courses/{course_id}:
    $ref: paths/admin_courses_{course_id}.yml
  /admin/courses/{course_id}/import:
    $ref: paths/admin_courses_{course_id}_import.yml
  /admin/courses/{course_id}/sync:
    $ref: paths/admin_courses_{course_id}_sync.yml
  /admin/courses/{course_id}/assignments:
    $ref: paths/admin_courses_{course_id}_assignments.yml
  /admin/courses/{course_id}/enable:
    $ref: paths/admin_courses_{course_id}_enable.yml
  /admin/courses/{course_id}/disable:
    $ref: paths/admin_courses_{course_id}_disable.yml
  /admin/courses/{course_id}/assignment/{assignment_id}/disable:
    $ref: paths/admin_courses_{course_id}_assignment_{assignment_id}_disable.yml
  /admin/courses/{course_id}/assignment/{assignment_id}/enable:
    $ref: paths/admin_courses_{course_id}_assignment_{assignment_id}_enable.yml
  /admin/courses/{course_id}/members:
    $ref: paths/admin_courses_{course_id}_members.yml
  /admin/users:
    $ref: paths/admin_users.yml
  /admin/users/{cwid}/enable:
    $ref: paths/admin_users_{cwid}_enable.yml
  /admin/users/{cwid}/disable:
    $ref: paths/admin_users_{cwid}_disable.yml
  /admin/users/{cwid}/admin:
    $ref: paths/admin_users_{cwid}_admin.yml
  /user:
    $ref: paths/user.yml
  /user/credentials:
    $ref: paths/user_credentials.yml
  /user/credentials/{credential_id}/disable:
    $ref: paths/user_credentials_{credential_id}_disable.yml
  /user/credentials/{credential_id}/public:
    $ref: paths/user_credentials_{credential_id}_public.yml
  /user/credentials/{credential_id}/private:
    $ref: paths/user_credentials_{credential_id}_private.yml
  /instructor/courses/{course_id}/assignment/{assignment_id}/user/{user_id}/extensions/{extension_id}/approve:
    $ref: >-
      paths/instructor_courses_{course_id}_assignment_{assignment_id}_user_{user_id}_extensions_{extension_id}_approve.yml
  /instructor/courses/{course_id}/assignment/{assignment_id}/user/{user_id}/extensions/{extension_id}/deny:
    $ref: >-
      paths/instructor_courses_{course_id}_assignment_{assignment_id}_user_{user_id}_extensions_{extension_id}_deny.yml
  /instructor/courses/{course_id}/policies:
    $ref: paths/instructor_courses_{course_id}_policies.yml
  /instructor/courses/{course_id}:
    $ref: paths/instructor_courses_{course_id}.yml
  /instructor/courses/{course_id}/enrollments:
    $ref: paths/instructor_courses_{course_id}_enrollments.yml
  /student/courses/{course_id}:
    $ref: paths/student_courses_{course_id}.yml
  /student/enrollments:
    $ref: paths/student_enrollments.yml
  /student/courses/{course_id}/assignments:
    $ref: paths/student_courses_{course_id}_assignments.yml
  /tasks:
    $ref: paths/tasks.yml
  /tasks/{task_id}:
    $ref: paths/tasks_{task_id}.yml
components:
  securitySchemes:
    OpenIDC:
      type: openIdConnect
      openIdConnectUrl: https://localhost.dev/auth/application/o/gradingadmin/.well_known
