spring:
  application:
    name: Grading Admin Service
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:postgresql}:${DB_PORT:5432}/${PG_DB:gradingadmindb}
    username: ${PG_USER:admin}
    password: ${PG_PASS:?database password required}
  web:
    resources:
      add-mappings: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER:http://localhost/application/o/gradingadmin/.well-known/openid-configuration}
  jpa:
    hibernate:
      ddl-auto: update
server:
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /api