spring:
  profiles:
    default: development
  application:
    name: Grading Admin Service
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost.dev}:${DB_PORT:5432}/${PG_DB:gradingadmindb}
    username: ${PG_USER:admin}
    password: ${PG_PASS:?database password required}
  web:
    resources:
      add-mappings: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER:https://localhost.dev/auth/application/o/grading-admin/}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  error:
    whitelabel:
      enabled: false

grading-admin:
  external-services:
    canvas:
      endpoint: https://elearning.mines.edu/
      teacher-enrollment-name: "TeacherEnrollment"
      student-enrollment-name: "StudentEnrollment"
      ta-enrollment-name: "TaEnrollment"
    s3:
      uri: ${S3_URI:https://localhost.dev:9000}
      access_key: ${MINIO_ROOT_USER:admin}
      secret_key: ${S3_SECRET_KEY:?s3 secret key required}
    rabbitmq:
      uri: amqp://${RABBITMQ_USER:admin}:${RABBITMQ_PASSWORD:?rabbitmq password required}@${RABBITMQ_HOST:localhost.dev:5672}
