spring:
  profiles:
    default: development
  application:
    name: Grading Admin Service
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost.dev}:${DB_PORT:5432}/${PG_DB:gradingadmindb}
    username: ${PG_USER:admin}
    password: ${PG_PASS:?database password required}
  web:
    resources:
      add-mappings: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER:https://localhost.dev/auth/application/o/grading-admin/}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  error:
    whitelabel:
      enabled: false

grading-admin:
  endpoints:
    canvas: https://elearning.mines.edu/