serverConfig:
  port: 80
  basePath: /api/policies

policyConfig:
  trustedServer: "https://localhost.dev"

rabbitMqConfig:
  username: "admin"
  password: "changeme!"
  endpoint: "localhost.dev"
  exchangeName: "exchange"
  port: 5672

