serverConfig:
    port: 80
    basePath: /api/policies
    trustedCA: /opt/certs/localhost.CA.crt

policyConfig:
    trustedServer: "https://localhost.dev"

rabbitMqConfig:
    username: "admin"
    password: "changeme!"
    endpoint: "localhost.dev"
    exchangeName: "grading-admin-message-exchange"
    port: 5672
