// import { useState } from 'react'
// import reactLogo from '../assets/react.svg'
// import viteLogo from '/vite.svg'
// import '../App.css'

// export function HomePage() {
// const [count, setCount] = useState(0)
    
//   return (
//     <>
//       <div>
//         <a href="https://vite.dev" target="_blank">
//           <img src={viteLogo} className="logo" alt="Vite logo" />
//         </a>
//         <a href="https://react.dev" target="_blank">
//           <img src={reactLogo} className="logo react" alt="React logo" />
//         </a>
//       </div>
//       <h1>Vite + React</h1>
//       <div className="card">
//         <button onClick={() => setCount((count) => count + 1)}>
//           count is {count}
//         </button>
//         <p>
//           Edit <code>src/App.tsx</code> and save to test HMR
//         </p>
//       </div>
//       <p className="read-the-docs">
//         Click on the Vite and React logos to learn more
//       </p>
//     </>
//   );
// }

import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "../lib/api/v1"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
  baseUrl: "https://localhost.dev/api/",
});
const $api = createClient(fetchClient);

export function HomePage() {
  const { data, error, isLoading } = $api.useQuery(
    "put",
    "/admin/course/new/{canvas_id}",
    {
      params: {
        path: { canvas_id: "5" },
      },
    },
  );

  if (isLoading || !data) return "Loading...";

  if (error) return `An error occured: ${error.error_message}`;

  return <div>{data.canvas_id}</div>;
};
