spring:
  profiles:
    default: development
  application:
    name: packtrain-service
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost.dev}:${DB_PORT:5432}/${PG_DB:gradingadmindb}
    username: ${PG_USER:admin}
    password: ${PG_PASS:?database password required}
  web:
    resources:
      add-mappings: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER:https://localhost.dev/auth/application/o/grading-admin/}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  mustache:
    check-template-location: false

server:
  error:
    whitelabel:
      enabled: false

grading-admin:
  # needs to be 16, 32, or 64 bytes long - this should also be randomly generated.
  secret-key: ${SECRET_KEY:password91023451}
  time-zone: "America/Denver"
  external-services:
    canvas:
      enabled: true
      disable-write: ${CANVAS_DISABLE_WRITE:false}
      endpoint: https://elearning.mines.edu/
      teacher-enrollment-name: "TeacherEnrollment"
      student-enrollment-name: "StudentEnrollment"
      ta-enrollment-name: "TaEnrollment"
    s3:
      enabled: true
      uri: ${S3_URI:https://localhost.dev:9000}
      access-key: ${MINIO_ROOT_USER:admin}
      secret-key: ${S3_SECRET_KEY:?s3 secret key required}
    rabbitmq:
      enabled: true
      uri: ${RABBITMQ_HOST:amqp://localhost.dev:5672}
      user: ${RABBITMQ_USER:admin}
      password: ${RABBITMQ_PASSWORD:?rabbitmq password required}
      exchange-name: "grading-admin-message-exchange"
    policy-server:
      enabled: true
      uri: ${POLICY_SERVER_URI:https://localhost.dev/api/policies}
    gradescope:
      enabled: true
      uri: https://gradescope.com
