name: CI

on:
  push:

jobs:
  java-test:
    name: Run java tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 23
          cache: 'maven'
          cache-dependency-path: 'grading-admin-service/pom.xml'

      - name: Build Project
        run: |
          mvn compile
        working-directory: grading-admin-service
      - name: Run Java Tests
        run: |
           mvn test
        working-directory: grading-admin-service

